apiVersion: apps/v1
kind: Deployment
metadata:
   name: simple-web
   labels:
    app: simple-web
spec:
  selector:
    matchLabels:
      app: simple-web
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - name: myapp
        image: dierkingni/simple-web
        ports:
        - containerPort: 80